<template>
  <header class="main-header">
    <div class="main-header-content">
      <router-link to="/" class="logo"
        ><span>arno</span><span>junio</span></router-link
      >
      <nav class="header-menu">
        <ul>
          <li><router-link to="/blog">Blog</router-link></li>
          <li>
            <router-link to="/about">{{ text.header }}</router-link>
          </li>

          <li>
            <div class="dropdown-list">
              <div @click="$emit('toggle-lang')" class="">
                <span
                  :class="[
                    this.isPtBr
                      ? 'flag-icon flag-icon-br'
                      : 'flag-icon flag-icon-us',
                    'dropdown-content',
                  ]"
                ></span>
                <span class="country">
                  <template v-if="this.isPtBr"> Português </template>
                  <template v-else> English </template>
                </span>
              </div>
              <div @click="$emit('toggle-lang')">
                <span
                  :class="[
                    this.isPtBr
                      ? 'flag-icon flag-icon-us'
                      : 'flag-icon flag-icon-br',
                    'dropdown-content',
                  ]"
                ></span>
                <span class="country">
                  <template v-if="this.isPtBr"> English</template>
                  <template v-else> Português </template>
                </span>
              </div>
            </div>
          </li>
          <li>
            <i
              @click="$emit('toggle-theme')"
              :class="[this.isDay ? 'fas fa-moon' : 'fas fa-sun']"
              :title="[this.isDay ? 'Modo Escuro' : 'Modo Claro']"
            ></i>
          </li>
        </ul>
      </nav>
    </div>
  </header>
</template>

<script>
export default {
  name: "Header",
  props: {
    text: Object,
    isDay: Boolean,
    isPtBr: Boolean
  },
  data() {
    return {};
  },
  methods: {},
  mounted() {
    /* if (this.cookies.get("theme") == "day") {
      this.isDay = true;
    }else{
      this.isDay = false;
    }*/
  },
};
</script>

<style language="css">
.app-active-link {
  color: #f90;
  border-bottom: #f90;
}
.dropdown-list {
  position: relative;
  display: inline-block;
  margin: 10px;
}
.dropdown-list div {
  padding: 10px 10px;
  cursor: pointer;
  height: 100%;
  min-width: 136px;
  font-size: 1.2em;
  font-weight: 500;
  color: var(--main-color) !important;
}
.dropdown-list .country {
  color: var(--main-color) !important;
}
.dropdown-list div:last-child {
  display: none;
  position: absolute;
  top:40px;
  box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
  z-index: 1;
}
/*
.dropdown-list:hover div:last-child {
  display: block;
 /* -webkit-animation: bounce-in-top 1.1s both;
  animation: bounce-in-top 1.1s both;
  -animation: example 0.5s;
  -webkit-animation: example 0.5s;
  
  
}*/
/* ----------------------------------------------
 * Generated by Animista on 2022-1-30 22:19:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-top
 * ----------------------------------------
 */
@-webkit-keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-30px);
    transform: translateY(-30px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-15px);
    transform: translateY(-15px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-1px);
    transform: translateY(-1px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes example {
    from {
        top: 0;
        opacity: 0;
    }
    to {
        top: 40px;
        opacity: 1;
    }
    
}
</style>
